#ifndef APP_CONFIG_H
#define APP_CONFIG_H

#define VOLTS_TO_ADC(v) ((v)*1023 * 3 / (13 * 2.56))

#define TIMER1_PRESCALER (8)
#define TIMER2_PRESCALER (64)

#define DYNAMO_FREQ_TO_CTR(f) ((F_CPU/(f*TIMER1_PRESCALER)))
#define SECONDS_TO_TIM2_REVS(s) ((s*(F_CPU/TIMER2_PRESCALER))/255)

#define STOPPING_THRESHOLD (SECONDS_TO_TIM2_REVS(15))
#define DRIVING_THRESHOLD (SECONDS_TO_TIM2_REVS(2))
#define DYNAMO_FREQUENCY_DRIVING (DYNAMO_FREQ_TO_CTR(150))

#define BRAKE_THRESHOLD_SCALE (64)
#define BRAKING_THRESHOLD (4*BRAKE_THRESHOLD_SCALE)

#define DIM_LIGHT_OCR (255*9/10)

#define TURN_ON_LIMIT_STEP (5)
#define TURN_ON_LIMIT_MAX (50 + TURN_ON_LIMIT_STEP)

#define MAX_DISCHARGE_VALUE (VOLTS_TO_ADC(3.5))
#define MIN_CHARGE_VALUE (VOLTS_TO_ADC(3.5))
#define MAX_CHARGE_VALUE (VOLTS_TO_ADC(8.9))
#define CHARGE_DISCHARGE_SPAN (VOLTS_TO_ADC(0.2))
#define CHARGE_VOLTAGE_STEP (VOLTS_TO_ADC(0.02))
#define DYNAMO_FREQUENCY_STEP_DOWN_TIMING (50)
#define DYNAMO_FREQUENCY_STEP_UP_TIMING (1)
#define DYNAMO_FREQUENCY_DANGER_VOLTAGE (DYNAMO_FREQ_TO_CTR(480))

#endif