#ifndef APP_CONFIG_H
#define APP_CONFIG_H

#define VOLTS_TO_ADC(v) ((v)*1023 * 3 / (13 * 2.56))
#define ADC_TO_MV(adc) ((adc) * ((13 * 2.56 * 1000) / (1023 * 3)))
#define ADC_TO_MV_OUTPUT(adc) ((adc) * ((20 * 2.56 * 1000) / (1023 * 10)))

#define TIMER1_PRESCALER (8)
#define TIMER2_PRESCALER (64)
#define TIMER1_TOP (0x1FF)

#define SECONDS_TO_TIM1_REVS(s) ((s * (F_CPU / TIMER1_PRESCALER)) / TIMER1_TOP)
#define SECONDS_TO_TIM2_REVS(s) ((s * (F_CPU / TIMER2_PRESCALER)) / 255)

#define STOPPING_THRESHOLD (SECONDS_TO_TIM2_REVS(15))
#define DRIVING_THRESHOLD (SECONDS_TO_TIM2_REVS(2))
#define DYNAMO_FREQUENCY_DRIVING (150)

#define BRAKE_THRESHOLD_SCALE (64)
#define BRAKING_THRESHOLD (2.5 * BRAKE_THRESHOLD_SCALE)
#define BRAKING_TIMING (SECONDS_TO_TIM2_REVS(0.025))

#define DIM_LIGHT_OCR (255 * 3 / 10)

#define BRAKE_LIGHT_TIMING (SECONDS_TO_TIM2_REVS(0.8))

#define TURN_ON_LIMIT_STEP (10)
#define TURN_ON_LIMIT_MAX (0x1FF)

#define MAX_DISCHARGE_VALUE (VOLTS_TO_ADC(3.5))
#define MAX_CHARGE_VALUE (VOLTS_TO_ADC(9.5))
#define MAX_CHARGE_VALUE_OVERVOLTAGE (VOLTS_TO_ADC(8.9))
#define CHARGE_DISCHARGE_SPAN (VOLTS_TO_ADC(1))
#define CHARGE_VOLTAGE_STEP (VOLTS_TO_ADC(0.5))
#define DYNAMO_FREQUENCY_STEP_DOWN_TIMING (50)
#define DYNAMO_FREQUENCY_STEP_UP_TIMING (1)
#define DYNAMO_FREQUENCY_DANGER_VOLTAGE (600)

#define MPPT_STEP (SECONDS_TO_TIM2_REVS(0.4))
#define OVERVOLTAGE_TIMING (SECONDS_TO_TIM2_REVS(0.1))
#define MAX_MPPT_STEP (8)
#define MIN_MPPT_STEP (1)
#define MIN_VOLTAGE_CHANGE (50)

#define MIN_SEARCH_SCAN_INTERVAL_SECONDS (4)
#define MAX_SEARCH_SCAN_INTERVAL_SECONDS (32)
#define SEARCH_STEP (10)
#define SINKING_THRESHOLD (4)
#define RISING_THRESHOLD (1)

#define PWM_DUTY_CYCLE_MAX (TIMER1_TOP)
#define FAST_FREQ_MEAS_REVS (SECONDS_TO_TIM1_REVS(0.01))
#define FREQ_MEAS_LIMIT_REVS (SECONDS_TO_TIM1_REVS(0.05))

#endif